### ISSUE TITLE
I can't get intellisense to work

### ISSUE THREAD

**Issue by jimfoye** [ionide/ionide-vscode-fake#6]
I did a fresh install of VS Code today. I've installed the two ionide F# packages, and nothing else. I haven't changed any options.

Intellisense will not work. I press Ctrl-Space, and see a "Loading..." message, but nothing every happens. True for both .fs and .fsx files.

Color syntax is OK, and FSI works (after I added to the path).

I opened Developer Tools and saw some errors:

[Plugin Host] Uncaught Exception:  Error: spawn C:\Users\James Foye\.vscode\extensions\Ionide.Ionide-fsharp/bin/FsAutoComplete.Suave.exe ENOENT
[Plugin Host] Error: spawn C:\Users\James Foye\.vscode\extensions\Ionide.Ionide-fsharp/bin/FsAutoComplete.Suave.exe ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
Error: spawn C:\Users\James Foye\.vscode\extensions\Ionide.Ionide-fsharp/bin/FsAutoComplete.Suave.exe ENOENT: Error: spawn C:\Users\James Foye\.vscode\extensions\Ionide.Ionide-fsharp/bin/FsAutoComplete.Suave.exe ENOENT
    at exports._errnoException (util.js:837)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178)
    at onErrorNT (internal/child_process.js:344)
    at doNTCallback2 (node.js:441)
    at process._tickCallback (node.js:355)
[uncaught exception]: TypeError: Cannot convert object to primitive value
TypeError: Cannot convert object to primitive value
    at new Error (native)
    at Client.trackException (C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\applicationinsights\Library\Client.js:67:25)
    at e.log (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:90:22274)
    at t.handleEvent (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:31955)
    at t.e.publicLog (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:29133)
    at t.e.flushErrorBuffer (file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:27142)
    at file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:45:27002
Uncaught TypeError: Cannot convert object to primitive value

Note that I don't have this on my system:

C:\Users\James Foye\.vscode\extensions\Ionide.Ionide-fsharp/bin/FsAutoComplete.Suave.exe

But I do have this:

C:\Users\James Foye\.vscode\extensions\Ionide.Ionide-fsharp-1.1.0\bin\FsAutoComplete.Suave.exe

**Comment by Gleb-Kazmenkov** [comment]
I have exactly the same error on OS X + vs code.
(paket also searches for the '/Users/glebk/.vscode/extensions/Ionide.Ionide-Paket/bin/paket.exe', when automatic installation (F1 -> "ext install") installs to  '/Users/glebk/.vscode/extensions/Ionide.Ionide-Paket**-1.0.2**'

**Comment by Krzysztof-Cieslak** [comment]
Discussed in https://github.com/ionide/ionide-vscode-fsharp/issues/27
